name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # This branch is where your code lives

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # This means publish everything from the root of your repository
